# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence', models.TextField()),
                ('index', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
